### PR TITLE
relax Liquid dependency

### PR DESCRIPTION
**Pull request by afeld**
Tested w/ Liquid 3.0.1.

### CODE REVIEW

**Comment by bdesham** [comment]
Thanks!

**Comment by afeld** [comment]
Thank _you_! Mind releasing a new version when you get a moment?

**Comment by bdesham** [comment]
Yeah, that’s done. I was happy to merge the PR from my phone while laying in bed but I wasn’t about to get up to push the new Gem :grin:

**Comment by afeld** [comment]
Long live the jammies merge :beers:

**Pull request merged**
